spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.eumji.mybatisxml.vo

  mapper-locations: classpath:mapper/*Mapper.xml


