spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jdbc

  #＃DDL模式。这实际上是“hibernate.hbm2ddl.auto”属性的快捷方式。
  #默认使用嵌入式数据库 “创建删除” ，否则为“否”。
  # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
  jpa:
    hibernate:
      ddl-auto: update
