

eumji:
  user:
    userName: zhangsan
    address: 湖南张家界
    phone: 185744xxxxx

  random:
    #随机字符串value
    strValue: ${random.value}
    #随机int型value
    intValue: ${random.int}
    #随机long型value
    longValue: ${random.long}
    #随机uuid
    uuidValue: ${random.uuid}
    #区间value
    rangeValue: ${random.int[10000,20000]}
server:
  port: 8088
